version: "2.17.2"
services:
  frontend:
    image: movie-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8078:80"
    depends_on:
      - backend
  backend:
    image: movie-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8079:8001"
